### ISSUE TITLE
Invocation Response error not being propagated from: provider to actor, actor to host

### ISSUE THREAD

**Issue by jose-acevedoflores** [wascc/wascc-host#101]
Errors that happen in a provider are not being propagated to the actor. 

When digging around the code found that the dispatch has a match block on the InvocationResponse error that looks like:
```rust
// dispatch method of  Dispatcher in dispatch.rs

        match resp {
            Ok(r) => match r.error {
                Some(e) => Err(format!("Invocation failure: {}", e).into()),
                None => Ok(r.msg),
            },
            Err(e) => Err(Box::new(e)),
        }
```

meanwhile the `wapc_host_callback` function of inthost.rs has a match block that doesn't check for an InvocationResponse error:
```rust 
//  wapc_host_callback  function in inthost.rs

    match bus.invoke(&invoke_subject, inv) {
        Ok(inv_r) => Ok(inv_r.msg),
        Err(e) => Err(Box::new(errors::new(errors::ErrorKind::HostCallFailure(
            e.into(),
        )))),
``` 

I wrote an integration test to play with it some more and found out the same error check is missing in the match block of the `call_actor` method in src/lib.rs

I patched it in my fork and can submit a PR for further discussion.

**Comment by autodidaddict** [comment]
Good catch. Lots of stuff got rewritten when the message bus was put in and it looks like I didn't grab the invocation failure there

**Comment by jose-acevedoflores** [comment]
awesome, I'll put the pull request out then.
