### ISSUE TITLE
Consider creating Cargo features for some things

### ISSUE THREAD

**Issue by rylev** [wascc/wascc-host#17]
Some aspects of the wascc-host library are not useful for all use cases, and it might be better for compile times to have those behind feature flags. For instance, some (most?) users will not likely need a gantry client. Also, reading Host manifests from json and yaml files introduces two dependencies that might not be needed. 

A quick experiment where I put `gantryclient`, `serde_json`, and `serde_yaml` behind feature flags led to clean builds compiling one minute faster.

**Comment by autodidaddict** [comment]
We've definitely considered using cargo features for a number of things. Would you mind submitting a PR for the features you've created? This sounds like there's 2 features here, `gantryclient` and `hostmanifest` ?
