### ISSUE TITLE
CNCF SIG-Runtime call for participation

### ISSUE THREAD

**Issue by raravena80** [wascc/wascc-host#25]
Hi @autodidaddict and waSCC community, (I couldn't find a mailing list so opening an issue here, it can be closed after it's read)

I'm one of the co-chairs for [CNCF SIG-Runtime](https://github.com/cncf/sig-runtime) and looking for folks interested in participating. Anything that you’d like to discuss and/or contribute with regards to runtime related open source projects and items. We believe wa runtimes are [very applicable](bit.ly/sig-runtime-roadmap).

We [meet](https://bit.ly/cncf-sig-runtime-meeting-notes) the first and third Thursday of the month at 8:00 am PT. Feel free to add any items to the meeting agenda and feel free to share. We also have [a ML you can subscribe to](https://lists.cncf.io/g/cncf-sig-runtime/).

Thanks!

**Comment by autodidaddict** [comment]
Thanks for thinking of us. I'll pass the word along. I'm presenting at s virtual conference during the next meeting but I will be sure to attend the next one.

**Comment by raravena80** [comment]
@autodidaddict happy to have you present/discuss the project at our SIG-Runtime meeting in the future. Thanks!

**Comment by autodidaddict** [comment]
I'll hopefully be attending the next meeting.
