### ISSUE TITLE
Middleware should support short-circuiting

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-host#33]
Right now the middleware chains are "all or nothing". In other words, the middleware gets a chance to execute and, if successful, the next middleware in the chain is invoked. 

We should be able to support a kind of middleware that can request that the invocation chain be stopped early, _even if nothing went wrong_. For example, you might put in middleware that automatically replies to certain invocations with a custom `InvocationResponse` without ever invoking the real target. This can't be done in today's middleware implementation.

The current middleware trait:

```rust
pub trait Middleware: Send + Sync + 'static {
    fn actor_pre_invoke(&self, inv: Invocation) -> Result<Invocation>;
    fn actor_post_invoke(&self, response: InvocationResponse) -> Result<InvocationResponse>;
    fn capability_pre_invoke(&self, inv: Invocation) -> Result<Invocation>;
    fn capability_post_invoke(&self, response: InvocationResponse) -> Result<InvocationResponse>;
}
```
This trait will need to be revised in some way such that middleware can be inserted into the middleware execution chain in a way that will allow the chain to optionally be stopped at the middleware and have the host not continue down the chain to the real target of the execution.

**Comment by autodidaddict** [comment]
One potential way to do this would be to add two more functions to the middleware trait:

```rust
fn actor_invoke(&self, handler: InvocationHandler) -> Result<InvocationResponse>;
fn capability_invoke(&self, handler: InvocationHandler> -> Result<InvocationResponse>;
```

This would allow the middleware to perform whatever logic it wants before and after, as well as make a decision as to whether it will actually invoke the handler.

In other middleware frameworks, the type of middleware is separated into three categories: `pre`, `post`, and `around`. The above trait would represent an `around` middleware.

**Comment by andrisak** [comment]
I had a look at this and I'm wondering if the return type for `actor_invoke` and `capability_invoke` needs to contain some more information, for example:
```rust
pub enum InvocationStatus {
    Invoked(Result<InvocationResponse>), // signal to continue executing middlewares
    ShortCircuit(Result<InvocationResponse>), // signal to stop executing middlewares
    NotInvoked,
}
```
`NotInvoked` would be used to handle the special case when no middleware has invoked the operation and there is no `InvocationResponse` available (likely to a bug in the middlewares or their configuration). The `post_invoke` in the middleware can/should be skipped in this case (there is no `InvocationResponse` to pass to it). Or does it break an invariant for post_invoke?

Is it necessary to differentiate between these three cases?

**Comment by autodidaddict** [comment]
:thinking: I wonder if the special case you're talking about when no middleware invoked the operation and there's no response available might be something better handled with the `Result` type than with a third variant.

For example, we could change the required signatures to:
```rust
fn actor_invoke(&self, handler: InvocationHandler) -> Result<MiddlewareResponse>;
fn capability_invoke(&self, handler: InvocationHandler> -> Result<MiddlewareResponse>;
```

where `Middleware` response is:

```rust
pub enum MiddlewareResponse {
    Continue(InvocationResponse),
    Halt(InvocationResponse)
}
```
In this way, the middleware can clearly indicate one of three things:

* Something went wrong (there's no response)
* The middleware did its job and does not need the chain to stop
* The middleware did its job and it wants the chain to terminate there.

Thoughts?

**Comment by andrisak** [comment]
Good suggestion. It's good that the middleware can also return a `Result` if the middleware processing fails.

I'll try to implement something along these lines.
