### ISSUE TITLE
RFC - Securing Actor-to-Actor Communications

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-host#42]
# Current State
Actor to actor calls have been supported for quite some time, even though it wasn't really all that well advertised. Today, if you want an actor to be able to call another actor, then you need to add the _callee_ actor's public key to the list of capabilities for which the _calling_ actor is granted access. This means ensuring that your actor signing process knows ahead of time the public key of the actor that needs to be invoked.

# What Needs to Change and Why
As more developers start using waSCC in _lattice_ mode, there's a much higher chance that developers will want to take advantage of actor-to-actor calling. The current security system around actor-to-actor calling is somewhat of a hack in that you have to pretend that the public key of an actor is a capability ID when signing the actor.

This can be a source of friction. For example:
* What if your development environment uses different signing keys than your production environment? This means that the signing script for the actor will be different in development than it is in production because when you change a signing key, you also change the public key.
* What if you have a very large number of actors? Managing the allow-list of actors that can be invoked might be a huge source of friction and worse, _boilerplate_.
* What if you have a group of actors you want to be able to communicate amongst themselves, but all other actors you want to be unable to invoke other actors

# Solution
This is where I'd like feedback. There are a number of possibilities here. We could further extend the wascap claims to include an actor-specific allow list (thereby removing the "hacky" smell from treating an actor's public key like a capid). We could perform some kind of OAuth access token flow where an actor must ask "the lattice" for an auth token in order to be able to call another actor, which would then allow the token dispenser to be some kind of pluggable code. 

We could also defer the authorization decision of "can actor A call actor B" to Open Policy Agent. Further, we could combine the OAuth access token dispenser with an OPA  decision to determine if the communication is allowed, etc.

The main solution requirement is that it **must not** introduce further friction, boilerplate, or annoying process steps into the developer workflow, and that it **must** be suitable for enterprise-grade security to prevent unauthorized communication.

**Comment by ewbankkit** [comment]
A couple of comments on the current text:

> Today, if you want an actor to be able to call another actor, then you need to add the actor's public key to the list of capabilities for which the actor is granted access.

Need to clarify which actor's public key should be added. e.g. "then you need to add the callee actor's public key to the list of capabilities for which the calling actor is granted access".

> What if your development environment uses different signing keys than your production environment? This means that the signing script for the actor will be different in QA than it is in production

`QA` -> `development` to keep environments consistent.

**Comment by autodidaddict** [comment]
Edited per your comments - thanks.

**Comment by autodidaddict** [comment]
When I think about the potential security issues, actor **A** calling actor **B** does not bother me on its face. What worries me is when **B**  has _more capabilities_ than A, and when A invokes some function of B's, it can easily be a means of _privilege escalation_.

Put in terms of requirements, if actor **A** invokes actor **B**, then nothing that **B** performs can _ever_ utilize more capabilities than those granted to **A**, even if **B** in isolation has been granted those capabilities. This must hold true no matter how many additional calls B makes. It could make 7 more calls through to actor **X**, which in turn invokes capabilities that were not granted.

My thinking on how to accomplish this is to stamp an invocation with the capabilities of the entity producing that invocation. This would then propagate through all subsequent invocations until the end of the chain. This feels very in line with the [nanoprocess](https://www.youtube.com/watch?v=TF-tXDRAEmg&feature=youtu.be) concept introduced by Lin Clark and the Bytecode Alliance.

By doing this, we basically create an ideal scenario:
* An invocation cannot be forged, because it must be signed with the capabilities of the entity producing it, this prevents an intruder that gained access to the lattice from creating fake invocations
* Privilege escalation is blocked because once an invocation has been stamped with capabilities, no capability outside that list can be utilized by any subsequent call.

**Comment by autodidaddict** [comment]
One possible counterpoint to this is when you're treating an actor like a gateway or a proxy. Actor **A** accepts some input from a message broker and then invokes actor **B** to process it, and actor **B** then goes to store that post-processed data in a key-value store. In the scenario described above (capabilities-signed invocations), this would require that actor **A** be signed with the `wascc:keyvalue` _and_ `wascc:messaging` capabilities. I'm fine with this limitation because it actually discourages the "privilege proxy" pattern... but it also forces people to think differently about their designs and it also may discourage using the actor-to-actor call pattern entirely.

If we weren't using capabilities-signed invocations, and instead using explicit actor-to-actor grants, then we'd be able to say that actor **A** is allowed to call actor **B**, and actor **B** has more capabilities than actor **A*** and that's okay.

**Comment by autodidaddict** [comment]
After mulling this over some more, I've come to at least one conclusion: we don't have enough evidence on how actor-to-actor communications will be used in large enough quantities where the existing "fake capability" mechanism becomes a burden. I also don't want to get us designed into a corner where we pick a particular model that can't be extended and prevents someone from using wascc.

## Proposal
Today the `set_auth_hook` function allows for a single function to determine if a given actor can be loaded. I propose that we change this to `set_authorizer` which would then take an `impl Authorizer`, where the `Authorizer` trait looks something like this:

```rust
pub trait Authorizer {
    fn can_load(claims: Claims<Actor>) -> bool;
    fn can_invoke(caller_claims: Claims<Actor>, target: InvocationTarget) -> bool;
}
```
Like all of the other claims-based enforcement checks, these would take place at the call site (as opposed to the recipient, which in lattice is out-of-process). The `can_load` function would serve the same purpose as the existing "auth hook" functionality, and `can_invoke` would become the ultimate arbiter of whether an actor is allowed to call _either_ a capability _or_ a capability provider.

Whatever logic is provided by the developer-supplied authorizer would be applied _after_ wascc host verifies that an actor can call a capability. If wascc host determines it cannot, the authorizer _will not be invoked_.

The default logic (provided by a new `DefaultAuthorizer`) struct would allow all actors to load and allow them all to invoke other actors and capabilities (because the waSCC host would already be enforcing the core actor capability calling rule)

It would be easier to just let the authorizer supplant all existing authorization logic, but I feel pretty strongly about making it physically impossible to accidentally remove one of the single most important security features of waSCC through a misread of documentation, etc. This is why I'm proposing that waSCC continue to always enforce the basic "can this actor invoke this capability" rule, and the developer-supplied authorizer would then have the option to refute that.
