### ISSUE TITLE
Actor claims should be provided during capability binding

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-host#45]
Today's capability providers are given nothing but the public key of the actor at the time of binding. While that might be enough for simple providers, complex or enterprise-specific providers might like to make additional decisions about how to bind (or to reject the binding outright) based on information contained in the actor claims (a good case here might be tags the provider is looking for, or maybe a specific issuer, etc).

**Comment by autodidaddict** [comment]
I think this one is a relatively simple code fix, though it will require that all first-party capability providers upgrade to a new version of the wascc-codec once this enhancement is in place. 

## Option 1 - Strongly-Typed Fields (Requires new Codec Version and ecosystem rebuild)
It would be really easy to just swap the `module` field with something like `module_claims` and have it be of type `Claims<Actor>`, but the claims type comes from `wascap`, and I don't want to force that dependency further up the chain as it might make it harder to support tiny/limited devices in the future.

We could either create a bunch of strongly-typed fields that contain the important data from the claims (issuer, subject, tags, capabilities array) or we could dump the entire structure as a `serde_json::Value` and let the other side deal with knowing the structure. 

I prefer picking the most important claims values and making them strongly-typed fields.

## Option 2 - Use the HashMap with specifically named values (no new codec required!)
In this option, we basically stuff into some custom configuration values data that came from the claims. We would use prefixed keys so as to avoid overriding regular configuration, e.g.
* `_wascc_claims_subject`
* `_wascc_claims_issuer`
* `_wascc_claims_capabilities` (comma-delimited list of capids)
* `_wascc_claims_name`
* `_wascc_claims_expires` - let the provider have access to when this actor's token expires
* `_wascc_claims_tags` (comma-delimited list of tags)

What I like about this option is that it's flexible in that we can continue to supply more metadata at the time of binding without ever forcing the entire ecosystem of capability providers to rebuild and take on a new version of `wascc-codec`.  This option is fully backwards compatible and the capability configuration will continue to serialize and deserialize as we add more metadata, and existing providers will continue to function without being aware of the new information.

**Comment by ewbankkit** [comment]
I vote for 2️⃣ for the flexibility.
