### ISSUE TITLE
lattice setup with nats server in gateway configuration mode

### ISSUE THREAD

**Issue by amar123deep** [wascc/wascc-host#53]
Description: Three nats server setup with gateway configuration mode. 

Following error message is received from nats-server 1 where the following command of the example on lattice is run

`RUST_LOG=cranelift_wasm=warn,info ./target/debug/wascc-host --manifest examples/lattice/host2.yaml`

`[ INFO ] Lattice Host: 10.0.0.81`
`[ INFO ] Initialized Message Bus (lattice)`
`[INFO ] Loaded native capability provider 'waSCC Extras (Internal)' v0.9.0 (2) for wascc:extras/default`
`[ INFO ] Native capability provider '(default,wascc:extras)' ready`
`[ INFO ] waSCC Host Manifest loaded, CWD: "wascc-host"`
`[ INFO ] Loaded native capability provider 'Default waSCC HTTP Server Provider (Actix)' v0.7.0 (2) for wascc:http_server/default`
`[ INFO  wascc_httpsrv] Dispatcher configured.`
`[INFO ] Native capability provider '(default,wascc:http_server)' ready`
`thread 'nats_subscriber_2_wasmbus.provider.wascc.http_server.default' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to de-serialize: invalid type: map, expected a string"', src/bus/lattice.rs:92:25`

Following error message is received from nats-server 2 where the following command of the example on lattice is run

`RUST_BACKTRACE=full RUST_LOG=cranelift_wasm=warn,info ./target/debug/wascc-host --manifest examples/lattice/host1.yaml` 
...
`[ INFO ] Lattice Host: 10.0.0.21`
`[ INFO ] Initialized Message Bus (lattice)`
`[ INFO ] Host ID is NB...`
`[ INFO ] Loaded native capability provider 'waSCC Extras (Internal)' v0.10.0 (2) for wascc:extras/default`
`[ INFO ] Native capability provider '(default,wascc:extras)' ready`
`[ INFO ] waSCC Host Manifest loaded, CWD: "wascc-host"`
`[INFO ] Discovered capability attestations for actor MB... wascc:http_server`
`[INFO ] Attempting to bind actor MB... to default,wascc:http_server`
`[INFO ] Binding subject: wasmbus.provider.wascc.http_server.default`
`Error: Error(CapabilityProvider("Failed to configure default,wascc:http_server - I/O error: No response"))`

**Comment by autodidaddict** [comment]
Can you try this against what's currently in master versus what's in crates.io?

**Comment by autodidaddict** [comment]
The failure is happening during binding. It looks as though the configuration is being sent from host2 to host1, but host1 isn't able to de-serialize the configuration. If you look closely, you can see that one of your hosts is running `0.9.0` and the other host is running `0.10.0`, which would certainly account for the inability for the two hosts to talk to each other.

**Comment by autodidaddict** [comment]
host2:
```
[ INFO ] Loaded native capability provider 'waSCC Extras (Internal)' v0.10.0 (2) for wascc:extras/defaul
```
host1:
```
[INFO ] Loaded native capability provider 'waSCC Extras (Internal)' v0.9.0 (2) for wascc:extras/default
```
0.9.0 and 0.10.0 are not compatible with each other.

**Comment by amar123deep** [comment]
Agree. I tried with the same version (0.9.0) from crate.io and i didn't get any error. 

There is another issue which I am not sure if it's a problem. Let's say we start messaging capability on a host. If we want to deploy an actor that would like to use that capability, then the host having the actor needs to know the ip address of the host, which has the required capability, for binding purpose. Is there way to provide some abstraction and discovery mechanism so that we don't need to hard code the ip address? 

Also killing a host that has an actor doesn't clean the binding on the host having the capability.

**Comment by autodidaddict** [comment]
I've filed #54, which should cover the "killing a host that has an actor doesn't clean the binding".

Just to clarify, you're talking about using the `wascc:messaging` capability, and not using the waSCC lattice distributed bus? In this case, the address (and credentials) of the broker need to be supplied to the wascc-host either through invoking `bind_actor` manually, or by reading a manifest. If you are worried about hard-coding IP addresses in the manifest, remember that you can do environment variable substitution on configuration values in the manifest file, which even supports defaults.

For example, a string like `${MY_BROKER_ADDRESS:127.0.0.1}` as a configuration value inside a binding in a manifest file will look for the env var `MY_BROKER_ADDRESS`, and if it doesn't find it, will resort to the default value of `127.0.0.1`

**Comment by amar123deep** [comment]
If an actor needs to send message to another actor, currently actor-sdk provides message broker [module](https://github.com/wascc/wascc-actor/blob/master/src/messaging.rs) and APIs which requires access to `wascc:messaging` capability. Do we need some message broker to support lattice?

**Comment by autodidaddict** [comment]
If you want one actor to call another, it can be done so using lattice if that call is out of process, or it can be done manually if it is done in-process. You'll need for the `calling` actor to be signed with a custom capability that is the public key of the `callee` actor for the security system to let this happen (there's another open issue for making this security more simplified as well).

The Gantry project has an example where a file stream actor makes a request of the catalog actor. This request can be in-process or it can be out-of-process using lattice, but again the module JWTs need to be signed to allow actor-to-actor invocations. You can see how the actor call takes place [here](https://github.com/wascc/gantry/blob/master/streams/src/lib.rs#L200).

**Comment by amar123deep** [comment]
I was trying out actor to actor communication with lattice. I sign actor A with public key of B and vice versa. Actor `A` sends a message to actor `B` on receiving a http request. To send a message from an actor `A` to actor `B`, following lines are added to the actor `A`.
`let reply_to: Option<&str> = Some("wasmbus://PUBLIC_KEY_ACTOR_A");`
`let subject = String::from("wasmbus://PUBLIC_KEY_ACTOR_B");` 
`let payload:Vec<u8>  = b"123".to_vec();`
`let _result = messaging::default().publish(&subject, reply_to, &payload);`

Actor B has following lines.
`actor_handlers! { codec::messaging::OP_DELIVER_MESSAGE => handle_event,`
                    `codec::core::OP_HEALTH_REQUEST => health }`

`fn handle_event(msg: codec::messaging::BrokerMessage) ->  HandlerResult<()> {`
    `let _result = messaging::default().publish(&msg.reply_to, None, &msg.body);`
    `Ok(())`
   `}`
I was wondering what I am doing wrong here.

**Comment by autodidaddict** [comment]
Actor to actor communication never explicitly uses wasmbus prefixes or the messaging provider.

The "provider" you're consuming is the public key of the actor you're calling. Did you take a look at the example of actor to actor calls in the Gantry repo?

Also, in actor to actor comms, you choose your own operation name, you likely would not reuse one.

Just to reiterate - user/developer code should never publish directly to wasmbus via messaging, because the plumbing for wasmbus could change. 

You want to use the untyped host binding from the actor sdk in actor a to call actor b:

untyped:: default ().call("public key of actor b", "operation name", .. payload ..)?;

**Comment by amar123deep** [comment]
The example is helpful. Just to make sure I understand it correctly, the `call` function is synchronous and single threaded, right? I wanted actor `B` to send back a message to actor `A` after it received a message from actor `A,` but I couldn't use the `call` function in actor `B` as it lead to deadlock.
