### ISSUE TITLE
Support for host annotations metadata

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-host#62]
The waSCC host should be able to accept an arbitrary list of tags that are associated with that particular host instance. These tags will ultimately be used by future features such as supporting affinity/anti-affinity when deciding whether or not a host can support a capability provider being deployed. These tags must also be discoverable via lattice inventory probes.

These tags should be passable to the generic runtime host (`wascc-host` binary) and to the `WasccHost` struct via the Rust API.

**Comment by autodidaddict** [comment]
These annotations or attributes could be key-value pairs instead of simple tags. The use case that makes me wonder about this is being able to specify an architecture value for the host (which will be required in scheduling/deploying/updating capability providers from a Gantry instance). We might have an attribute of `arch` with a value of `x86_64`. This could be a slippery slope, however, in that we then might want to define affinity / anti-affinity rules with more complex statements than just equality or inequality. 

Thoughts @bketelsen @ewbankkit @brooksmtownsend ? My personal opinion on this is that we should keep it as absolutely simple as possible to start with. We could satisfy the architecture question by just creating a tag `arch-x86_64` or `arch_aarch64`. However, well-known keys like `arch` might be beneficial when doing things like requesting the raw bytes for a capability provider from Gantry.

I'm okay with using key-value pairs as long as we keep an eye on potential scope creep in terms of defining the match rules for scheduling.

**Comment by ewbankkit** [comment]
Maybe use Kubernetes/Krustlet for inspiration and have string labels with string values (i.e. simple key-value)?
Some could be host managed, e.g. `arch` and `os`, others specified by the operator via command-line or manifest file.
https://github.com/deislabs/krustlet/blob/feb3101edd9711df5964554641f075e8951e6af6/crates/kubelet/src/node/mod.rs#L442-L498

**Comment by autodidaddict** [comment]
Yeah that's what I was leaning toward. We can auto-populate some of the values ourselves (like you say, `arch`, and `os`) but others can be injected and ultimately used for determining the outcome of scheduling auctions (#63)

**Comment by bketelsen** [comment]
Someone beat me to the "do what Krustlet does" suggestion.  That's my vote too.
GitHub <notifications@github.com> wrote:
“Yeah that's what I was leaning toward. We can auto-populate some of the values ourselves (like you say, arch, and os) but others can be injected and ultimately used for determining the outcome of scheduling auctions (#63)”
