### ISSUE TITLE
Consider making the error Sync + Send

### ISSUE THREAD

**Issue by TheNeikos** [wascc/wascc-host#74]
Currently the [error](https://docs.rs/wascc-host/0.11.0/wascc_host/errors/struct.Error.html) type used is neither `Send` nor `Sync`. I believe that top-level error types like these should always be Send + Sync. This allows for greater flexibility on the handling of errors as well as libraries that could be used (for example the `anyhow` crate needs its errors to be `Send + Sync`.

Is there a specific reason why they cannot be `Send + Sync`? I have looked through the code and parts of it seems to stem from the `wapc` crate. However I did not find a good reason for its existence, as it [is not used](https://github.com/wapc/wapc-rust/search?q=HostCallFailure&unscoped_q=HostCallFailure) there.

What do you think? I'd gladly cook up a PR to make this change.

**Comment by autodidaddict** [comment]
There's no reason other than evolution. There's been a mountain of refactoring since the beginning of this project and it's just a matter of oversight that the error type isn't send and sync.

**Comment by TheNeikos** [comment]
Alright, I will start with WAPC first, and then we could change this as well.
