### ISSUE TITLE
Host binary should gracefully fail when creating Gantry client with no NATS connectivity

### ISSUE THREAD

**Issue by autodidaddict** [wascc/wascc-host#91]
https://github.com/wascc/wascc-host/blob/9f914040732a3af1d712fce0c40750c757629751/src/bin.rs#L42

As pointed out by @brooksmtownsend , this line of code will fail if NATS isn't up and running locally. Since lattice and gantry are now the same feature, the assumption is that if you've compiled in lattice mode, then we will use the lattice connection as a gantry connection. However, we should have a more graceful way of handling this failure than we do right now.

**Comment by autodidaddict** [comment]
This is what the wascc-host binary (compiled with lattice/gantry enabled) will now do if it can't connect to a NATS endpoint:

```
target/debug/wascc-host 
[2020-09-28T14:27:58Z ERROR] Failed to create Gantry client. Check if NATS is running and client is configured properly.
[2020-09-28T14:27:58Z ERROR] Terminating host (no lattice connectivity)
```

**Comment by brooksmtownsend** [comment]
Nice. I think ensuring nobody gets stuck on having NATS running will be great for the developer experience

**Comment by autodidaddict** [comment]
Well, if you have lattice enabled as a feature, you _must_ have NATS. That's a requirement. The only way you can run waSCC host without NATS running is if you're on a non-lattice binary.
